apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  namespace: {{.Values.namespace}}
spec:
  app: {{.Values.name}}
  version: {{.Values.version}}
  {{- if .Values.region}}
  region: {{.Values.region}}
  {{else}}
  region: null
  {{- end}}
  {{- if .Values.canary_suffix}}
  canary_suffix: {{.Values.canary_suffix}}
  {{else}}
  canary_suffix: null
  {{- end}}
  {{- if .Values.overrides}}
  overrides: {{.Values.overrides}}
  {{else}}
  overrides: {}
  {{- end}}
