apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-config
data:
  key: value
  CATALINA_OPTS: {{.Values.CATALINA_OPTS}}
  JAVA_OPTS: {{.Values.JAVA_OPTS}}
  APPDYNAMICS_AGENT_ACCOUNT_NAME: {{.Values.APPDYNAMICS_AGENT_ACCOUNT_NAME}}
  APPDYNAMICS_AGENT_APPLICATION_NAME: {{.Values.APPDYNAMICS_AGENT_APPLICATION_NAME}}
  APPDYNAMICS_AGENT_TIER_NAME: {{.Values.APPDYNAMICS_AGENT_TIER_NAME}}
  APPDYNAMICS_CONTROLLER_HOST_NAME: {{.Values.APPDYNAMICS_CONTROLLER_HOST_NAME}}
  APPDYNAMICS_CONTROLLER_PORT: {{.Values.APPDYNAMICS_CONTROLLER_PORT}}
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: {{.Values.APPDYNAMICS_CONTROLLER_SSL_ENABLED}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
stringData:
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: {{.Values.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}}

---
{{- if .Values.createImagePullSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.createImagePullSecret}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        envFrom:
        - configMapRef:
            name: {{.Values.name}}-config
        - secretRef:
            name: {{.Values.name}}-secret
        resources:
          limits:
            cpu: 1
            memory: 1536Mi
          requests:
            cpu: 1
            memory: 1536Mi            