apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-primary

# mandatory annotation indicating primary service

  annotations:
    harness.io/primary-service: true
    name: usheer
    type: test123
  labels:
    app: bg-demo-app
    type: abc123
    new: saas
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: bg-demo-app