apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace.name}}
  {{- if .Values.namespace.annotated}}
  annotations:
    harness-created-by: {{.Values.namespace.createdBy | quote}}
    harness-last-deployed-by: {{.Values.namespace.lastDeployedBy | quote}}
    harness-ttl-hours: {{.Values.namespace.ttlHours | quote}}
    harness-last-deploy: {{.Values.namespace.lastDeploy | quote}}
    harness-preserve-data-days: {{.Values.namespace.preserveDays | quote}}
  {{- end}}