apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  namespace: {{.Values.namespace.name}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{.Values.name}}
spec:
  clusterIP: None
  ports:
    - port: {{.Values.servicePort1}}
      targetPort: {{.Values.serviceTargetPort1}}
      protocol: TCP
      name: {{.Values.servicePortName1}}
    - port: {{.Values.servicePort2}}
      targetPort: {{.Values.serviceTargetPort2}}
      protocol: TCP
      name: {{.Values.servicePortName2}}
  publishNotReadyAddresses: true  
  selector:
    app: {{.Values.name}}